/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IMC.java
 *
 * Created on 08/02/2012, 09:04:08
 */
package View;

import javax.swing.JOptionPane;
import java.text.DecimalFormat;

/**
 *
 * @author Familia-Silva
 */
public class IMC extends javax.swing.JFrame {

    double peso;
    double altura;
    double x;

    /** Creates new form IMC */
    public IMC() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtaltura = new javax.swing.JTextField();
        lblnome = new java.awt.Label();
        txtnome1 = new javax.swing.JTextField();
        lblnome1 = new java.awt.Label();
        txtpeso = new javax.swing.JTextField();
        lblnome2 = new java.awt.Label();
        btnsair = new java.awt.Button();
        btnanalisa1 = new java.awt.Button();
        btnlimpar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculo de IMC");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });
        txtaltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtalturaKeyReleased(evt);
            }
        });
        getContentPane().add(txtaltura);
        txtaltura.setBounds(20, 80, 360, 20);

        lblnome.setText("ALTURA");
        getContentPane().add(lblnome);
        lblnome.setBounds(20, 60, 60, 20);

        txtnome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome1);
        txtnome1.setBounds(20, 30, 360, 20);

        lblnome1.setText("NOME");
        getContentPane().add(lblnome1);
        lblnome1.setBounds(20, 10, 60, 20);

        txtpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesoActionPerformed(evt);
            }
        });
        txtpeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesoKeyReleased(evt);
            }
        });
        getContentPane().add(txtpeso);
        txtpeso.setBounds(20, 130, 360, 20);

        lblnome2.setText("PESO");
        getContentPane().add(lblnome2);
        lblnome2.setBounds(20, 110, 60, 20);

        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair);
        btnsair.setBounds(200, 170, 70, 24);

        btnanalisa1.setLabel("Analisar");
        btnanalisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalisa1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnanalisa1);
        btnanalisa1.setBounds(20, 170, 70, 24);

        btnlimpar.setLabel("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpar);
        btnlimpar.setBounds(110, 170, 70, 24);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-241)/2, 416, 241);
    }// </editor-fold>//GEN-END:initComponents

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalturaActionPerformed

    private void txtnome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome1ActionPerformed
 public static String converterDoubleString(double precoDouble) {
        /*Transformando um double em 2 casas decimais*/
        DecimalFormat fmt = new DecimalFormat("0.00");    //limita o número de casas decimais
        String string = fmt.format(precoDouble);
        String[] part = string.split("[,]");
        String preco = part[0]+"."+part[1];
        return preco;
    }
    private void txtpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesoActionPerformed
    public void calculoImc() {
        peso = Double.parseDouble(txtpeso.getText());
        altura = Double.parseDouble(txtaltura.getText());
        double x = peso / (altura * altura);
        //JOptionPane.showMessageDialog(null, x);
        if (x < 20) {

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: abaixo do peso");


        }
        if (x >= 20.01 && x <= 25) {
            //  x = Double.parseDouble(txtpeso.getText())/ (Double.parseDouble(txtaltura.getText())) * (Double.parseDouble(txtaltura.getText()));

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: Peso Ideal");

        }
        if (x >= 25.01 && x <= 30) {
            //    x = Double.parseDouble(txtpeso.getText()) / (Double.parseDouble(txtaltura.getText())) * (Double.parseDouble(txtaltura.getText()));

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: Sobrepeso");

        }
        if (x >= 30.01 && x <= 35) {
            //  x = Double.parseDouble(txtpeso.getText()) / (Double.parseDouble(txtaltura.getText())) * (Double.parseDouble(txtaltura.getText()));

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: Obesidade Moderada");

        }
        if (x >= 35.01 && x <= 40) {
            // x = Double.parseDouble(txtpeso.getText()) / (Double.parseDouble(txtaltura.getText())) * (Double.parseDouble(txtaltura.getText()));

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: Obesidade Severa");

        }
        if (x >= 40.01 && x <= 50) {
            // x = Double.parseDouble(txtpeso.getText()) / (Double.parseDouble(txtaltura.getText())) * (Double.parseDouble(txtaltura.getText()));

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: Obesidade Morbida");

        }
        if (x > 50.01) {
            // x = Double.parseDouble(txtpeso.getText()) / (Double.parseDouble(txtaltura.getText())) * (Double.parseDouble(txtaltura.getText()));

            JOptionPane.showMessageDialog(null, txtnome1.getText().toUpperCase() + "\nSeu IMC é " + converterDoubleString(x) + ". \nEstado: Super-Obesidade");

        }
    }
    private void btnanalisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalisa1ActionPerformed
        // TODO add your handling code here:
        if (txtnome1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite seu nome.");
            txtnome1.requestFocus();
        } else if (txtaltura.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a altura.");
            txtaltura.requestFocus();
        } else if (txtpeso.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o peso.");
            txtpeso.requestFocus();
        } else {
            calculoImc();
            txtaltura.setText("");
            txtnome1.setText("");
            txtpeso.setText("");
            txtnome1.requestFocus();
        }


    }//GEN-LAST:event_btnanalisa1ActionPerformed

    private void txtalturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalturaKeyReleased
        // TODO add your handling code here:
        txtaltura.setText(txtaltura.getText().replace(",", ".").replace("q", "").replace("w", "").replace("e", "").replace("r", "").replace("t", "").replace("y", "").replace("u", "").replace("i", "").replace("o", "").replace("p", "").replace("´", "").replace("[", "").replace("a", "").replace("s", "").replace("d", "").replace("f", "").replace("g", "").replace("h", "").replace("j", "").replace("k", "").replace("l", "").replace("ç", "").replace("~", "").replace("]", "").replace("|", "").replace("z", "").replace("x", "").replace("c", "").replace("v", "").replace("b", "").replace("n", "").replace("m", "").replace(";", "").replace("<", "").replace(">", "").replace("/", "").replace("^", "").replace("}", "").replace("º", "").replace("{", "").replace("ª", "").replace("'", "").replace("!", "").replace("@", "").replace("$", "").replace("%", "").replace("¨", "").replace("&", "").replace("*", "").replace("(", "").replace(")", "").replace("+", "").replace("-", "").replace("_", "").replace(")", "").replace("#", "").replace("?", "").replace("°", ""));
    }//GEN-LAST:event_txtalturaKeyReleased

    private void txtpesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesoKeyReleased
        // TODO add your handling code here:
        txtpeso.setText(txtpeso.getText().replace(",", ".").replace("q", "").replace("w", "").replace("e", "").replace("r", "").replace("t", "").replace("y", "").replace("u", "").replace("i", "").replace("o", "").replace("p", "").replace("´", "").replace("[", "").replace("a", "").replace("s", "").replace("d", "").replace("f", "").replace("g", "").replace("h", "").replace("j", "").replace("k", "").replace("l", "").replace("ç", "").replace("~", "").replace("]", "").replace("|", "").replace("z", "").replace("x", "").replace("c", "").replace("v", "").replace("b", "").replace("n", "").replace("m", "").replace(";", "").replace("<", "").replace(">", "").replace("/", "").replace("^", "").replace("}", "").replace("º", "").replace("{", "").replace("ª", "").replace("'", "").replace("!", "").replace("@", "").replace("$", "").replace("%", "").replace("¨", "").replace("&", "").replace("*", "").replace("(", "").replace(")", "").replace("+", "").replace("-", "").replace("_", "").replace(")", "").replace("#", "").replace("?", "").replace("°", ""));
    }//GEN-LAST:event_txtpesoKeyReleased

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        // TODO add your handling code here:
        txtaltura.setText("");
        txtnome1.setText("");
        txtpeso.setText("");
        txtnome1.requestFocus();
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IMC().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnanalisa1;
    private java.awt.Button btnlimpar;
    private java.awt.Button btnsair;
    private java.awt.Label lblnome;
    private java.awt.Label lblnome1;
    private java.awt.Label lblnome2;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtnome1;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables
}
